version: '3.8'

services:
  taskhub-sse:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["uv", "run", "python", "-m", "src.server", "--transport", "sse", "--host", "0.0.0.0", "--port", "8000"]

  taskhub-stdio:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: ["uv", "run", "python", "-m", "src.server", "--transport", "stdio"]

  taskhub-dev:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["uv", "run", "python", "-m", "src.server", "--transport", "sse", "--host", "0.0.0.0", "--port", "8000"]